name: Node.js CI
'on':
  - pull_request
  
jobs:
  tests:
    name: Rodar testes unitários
    runs-on: ubuntu-latest

    strategy:
       matrix:
        chunk: [1,2,3,4,5,6,7,8,9,10]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: jest
        run:  sh ./scripts/setupTestMatrix.sh ${{ matrix.chunk }} 10
